1）Sample tables

CREATE TABLE CCL.CODE_MAP (
    CODE_CATEGORY       VARCHAR(30),
    CODE_SUB_CATEGORY   VARCHAR(30),
    CODE_TYPE           VARCHAR(30),
    KEY1                VARCHAR(30),
    KEY2                VARCHAR(30),
    CODE_VALUE          VARCHAR(100)
);

CREATE TABLE FOS.API_MTM_REVAL (
    CUSTOMER_NUMBER     VARCHAR(20),
    DEAL_NUMBER         VARCHAR(20),
    DEAL_TYPE           VARCHAR(10),
    MTM_AMOUNT          DECIMAL(18,2),
    STATUS_CD           VARCHAR(10),
    LAST_UPDATE_TS      TIMESTAMP
);

CREATE TABLE INTERFACE.API_MTM_REVAL (
    CUST_NUM            VARCHAR(20),
    DEAL_NUM            VARCHAR(20),
    DEAL_TYPE           VARCHAR(10),
    CUR_MTM_AMT         DECIMAL(18,2),
    STATUS_CD           VARCHAR(10),
    LAST_UPD_TS         TIMESTAMP
);

CREATE TABLE INTERFACE.API_MTM_REVAL_STAR (
    CUST_NUM            VARCHAR(20),
    DEAL_NUM            VARCHAR(20),
    DEAL_TYPE           VARCHAR(10),
    CUR_MTM_AMT         DECIMAL(18,2)
);

CREATE TABLE RPT.MTM_REVAL_AUDIT (
    AUDIT_ID            BIGINT,
    CUST_NUM            VARCHAR(20),
    DEAL_NUM            VARCHAR(20),
    ACTION_CD           VARCHAR(20),
    AUDIT_TS            TIMESTAMP
);

CREATE TABLE INTERFACE.MTM_REVAL_HIST (
    CUST_NUM            VARCHAR(20),
    DEAL_NUM            VARCHAR(20),
    CUR_MTM_AMT         DECIMAL(18,2)
);

CREATE TABLE INTERFACE.MTM_REVAL_TMP_COPY (
    CUST_NUM            VARCHAR(20),
    DEAL_NUM            VARCHAR(20),
    CUR_MTM_AMT         DECIMAL(18,2)
);

2）Sample view
  CREATE VIEW INTERFACE.V_API_MTM_REVAL AS
SELECT
    F.CUSTOMER_NUMBER AS CUST_NUM,
    F.DEAL_NUMBER     AS DEAL_NUM,
    F.DEAL_TYPE       AS DEAL_TYPE,
    F.MTM_AMOUNT      AS CUR_MTM_AMT,
    F.LAST_UPDATE_TS  AS LAST_UPD_TS
FROM FOS.API_MTM_REVAL F;


3）Sample functions
  CREATE OR REPLACE FUNCTION INTERFACE.FN_GET_CODE_MAP_VALUE
(
    P_CODE_CATEGORY      VARCHAR(30),
    P_CODE_SUB_CATEGORY  VARCHAR(30),
    P_CODE_TYPE          VARCHAR(30),
    P_KEY1               VARCHAR(30),
    P_KEY2               VARCHAR(30)
)
RETURNS VARCHAR(100)
LANGUAGE SQL
READS SQL DATA
BEGIN ATOMIC
    DECLARE V_RESULT VARCHAR(100);

    SET V_RESULT = (
        SELECT CODE_VALUE
        FROM CCL.CODE_MAP
        WHERE CODE_CATEGORY = P_CODE_CATEGORY
          AND CODE_SUB_CATEGORY = P_CODE_SUB_CATEGORY
          AND CODE_TYPE = P_CODE_TYPE
          AND KEY1 = P_KEY1
          AND KEY2 = P_KEY2
        FETCH FIRST 1 ROW ONLY
    );

    RETURN COALESCE(V_RESULT, 'NA');
END;


CREATE OR REPLACE FUNCTION INTERFACE.FN_REL_DEMO
(
    P_CUST_NUM VARCHAR(20)
)
RETURNS VARCHAR(200)
LANGUAGE SQL
READS SQL DATA
BEGIN ATOMIC
    DECLARE V_OUT VARCHAR(200);

    SET V_OUT = (
        SELECT TRIM(V.CUST_NUM) || '-' ||
               INTERFACE.FN_GET_CODE_MAP_VALUE('MTM','STATUS','DEFAULT','A','B')
        FROM INTERFACE.V_API_MTM_REVAL V
        WHERE V.CUST_NUM = P_CUST_NUM
        FETCH FIRST 1 ROW ONLY
    );

    RETURN V_OUT;
END;


4）Sample procedures
  CREATE OR REPLACE PROCEDURE RPT.PR_AUDIT_MTM_REVAL
(
    IN P_CUST_NUM VARCHAR(20),
    IN P_DEAL_NUM VARCHAR(20),
    IN P_ACTION   VARCHAR(20)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    INSERT INTO RPT.MTM_REVAL_AUDIT
    (
        AUDIT_ID,
        CUST_NUM,
        DEAL_NUM,
        ACTION_CD,
        AUDIT_TS
    )
    VALUES
    (
        1,
        P_CUST_NUM,
        P_DEAL_NUM,
        P_ACTION,
        CURRENT TIMESTAMP
    );
END;

=============
  CREATE OR REPLACE PROCEDURE INTERFACE.PI_API_MTM_REVAL_DEMO
(
    IN P_CUST_NUM VARCHAR(20)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DECLARE V_STATUS VARCHAR(20);

    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE
    (
        CUST_NUM      VARCHAR(20),
        DEAL_NUM      VARCHAR(20),
        DEAL_TYPE     VARCHAR(10),
        CUR_MTM_AMT   DECIMAL(18,2)
    )
    WITH REPLACE
    ON COMMIT PRESERVE ROWS;

    DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE_ALL
    (
        CUST_NUM      VARCHAR(20),
        DEAL_NUM      VARCHAR(20),
        DEAL_TYPE     VARCHAR(10),
        CUR_MTM_AMT   DECIMAL(18,2)
    )
    WITH REPLACE
    ON COMMIT PRESERVE ROWS;

    SET V_STATUS = INTERFACE.FN_REL_DEMO(P_CUST_NUM);

    INSERT INTO SESSION.T_MTM_STAGE
    (
        CUST_NUM,
        DEAL_NUM,
        DEAL_TYPE,
        CUR_MTM_AMT
    )
    WITH BASE_DATA AS
    (
        SELECT
            V.CUST_NUM,
            V.DEAL_NUM,
            V.DEAL_TYPE,
            V.CUR_MTM_AMT
        FROM INTERFACE.V_API_MTM_REVAL V
        WHERE V.CUST_NUM = P_CUST_NUM

        UNION ALL

        SELECT
            I.CUST_NUM,
            I.DEAL_NUM,
            I.DEAL_TYPE,
            I.CUR_MTM_AMT
        FROM INTERFACE.API_MTM_REVAL I
        WHERE I.CUST_NUM = P_CUST_NUM
    )
    SELECT
        B.CUST_NUM,
        B.DEAL_NUM,
        B.DEAL_TYPE,
        B.CUR_MTM_AMT
    FROM BASE_DATA B;

    INSERT INTO SESSION.T_MTM_STAGE_ALL
    (
        CUST_NUM,
        DEAL_NUM,
        DEAL_TYPE,
        CUR_MTM_AMT
    )
    SELECT
        S.CUST_NUM,
        S.DEAL_NUM,
        S.DEAL_TYPE,
        S.CUR_MTM_AMT
    FROM SESSION.T_MTM_STAGE S;

    INSERT INTO INTERFACE.API_MTM_REVAL
    (
        CUST_NUM,
        DEAL_NUM,
        DEAL_TYPE,
        CUR_MTM_AMT,
        STATUS_CD,
        LAST_UPD_TS
    )
    SELECT
        S.CUST_NUM,
        S.DEAL_NUM,
        S.DEAL_TYPE,
        S.CUR_MTM_AMT,
        V_STATUS,
        CURRENT TIMESTAMP
    FROM SESSION.T_MTM_STAGE S;

    INSERT INTO INTERFACE.API_MTM_REVAL_STAR
    SELECT *
    FROM SESSION.T_MTM_STAGE_ALL;

    INSERT INTO INTERFACE.V_API_MTM_REVAL
    (
        CUST_NUM,
        DEAL_NUM,
        DEAL_TYPE,
        CUR_MTM_AMT,
        LAST_UPD_TS
    )
    SELECT
        CUSTOMER_NUMBER,
        DEAL_NUMBER,
        DEAL_TYPE,
        MTM_AMOUNT,
        LAST_UPDATE_TS
    FROM FOS.API_MTM_REVAL
    WHERE CUSTOMER_NUMBER = P_CUST_NUM;

    UPDATE INTERFACE.API_MTM_REVAL T
       SET STATUS_CD = 'ACTIVE',
           CUR_MTM_AMT = (
               SELECT S.CUR_MTM_AMT
               FROM SESSION.T_MTM_STAGE S
               WHERE S.DEAL_NUM = T.DEAL_NUM
               FETCH FIRST 1 ROW ONLY
           )
     WHERE T.CUST_NUM = P_CUST_NUM;

    UPDATE INTERFACE.V_API_MTM_REVAL V
       SET DEAL_TYPE = 'UPD'
     WHERE V.CUST_NUM = P_CUST_NUM;

    DELETE FROM INTERFACE.API_MTM_REVAL
     WHERE STATUS_CD = 'OLD';

    DELETE FROM INTERFACE.V_API_MTM_REVAL
     WHERE CUST_NUM = 'TO_DELETE';

    MERGE INTO INTERFACE.API_MTM_REVAL T
    USING SESSION.T_MTM_STAGE S
       ON T.DEAL_NUM = S.DEAL_NUM
    WHEN MATCHED THEN
         UPDATE SET
             T.CUR_MTM_AMT = S.CUR_MTM_AMT,
             T.STATUS_CD = 'MERGED'
    WHEN NOT MATCHED THEN
         INSERT
         (
             CUST_NUM,
             DEAL_NUM,
             DEAL_TYPE,
             CUR_MTM_AMT,
             STATUS_CD,
             LAST_UPD_TS
         )
         VALUES
         (
             S.CUST_NUM,
             S.DEAL_NUM,
             S.DEAL_TYPE,
             S.CUR_MTM_AMT,
             'NEW',
             CURRENT TIMESTAMP
         );

    MERGE INTO INTERFACE.V_API_MTM_REVAL V
    USING SESSION.T_MTM_STAGE S
       ON V.DEAL_NUM = S.DEAL_NUM
    WHEN MATCHED THEN
         UPDATE SET
             V.CUR_MTM_AMT = S.CUR_MTM_AMT
    WHEN NOT MATCHED THEN
         INSERT
         (
             CUST_NUM,
             DEAL_NUM,
             DEAL_TYPE,
             CUR_MTM_AMT,
             LAST_UPD_TS
         )
         VALUES
         (
             S.CUST_NUM,
             S.DEAL_NUM,
             S.DEAL_TYPE,
             S.CUR_MTM_AMT,
             CURRENT TIMESTAMP
         );

    CALL RPT.PR_AUDIT_MTM_REVAL(P_CUST_NUM, 'D001', 'DONE');

    INSERT INTO INTERFACE.MTM_REVAL_TMP_COPY
    (
        CUST_NUM,
        DEAL_NUM,
        CUR_MTM_AMT
    )
    SELECT
        CUST_NUM,
        DEAL_NUM,
        CUR_MTM_AMT
    FROM INTERFACE.API_MTM_REVAL;

    TRUNCATE TABLE INTERFACE.MTM_REVAL_HIST IMMEDIATE;
END;

----SELECT
    I.DEAL_TYPE,
    COUNT(*) AS CNT
FROM INTERFACE.API_MTM_REVAL I
JOIN FOS.API_MTM_REVAL F
  ON I.DEAL_NUM = F.DEAL_NUMBER
WHERE I.STATUS_CD = 'ACTIVE'
GROUP BY I.DEAL_TYPE
HAVING COUNT(*) > 1
ORDER BY I.DEAL_TYPE;

EXECUTE IMMEDIATE 'DELETE FROM INTERFACE.API_MTM_REVAL WHERE STATUS_CD = ''X''';44


  ----
  root_source_object	root_source_field	final_target_object	final_target_field	path	hop_count	path_relationship	confidence
FOS.API_MTM_REVAL	CUSTOMER_NUMBER	INTERFACE.V_API_MTM_REVAL	CUST_NUM	FOS.API_MTM_REVAL.CUSTOMER_NUMBER -> INTERFACE.V_API_MTM_REVAL.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	DEAL_NUMBER	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	FOS.API_MTM_REVAL.DEAL_NUMBER -> INTERFACE.V_API_MTM_REVAL.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	DEAL_TYPE	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	FOS.API_MTM_REVAL.DEAL_TYPE -> INTERFACE.V_API_MTM_REVAL.DEAL_TYPE	1	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	MTM_AMOUNT	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	FOS.API_MTM_REVAL.MTM_AMOUNT -> INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER

INTERFACE.V_API_MTM_REVAL	CUST_NUM	SESSION.T_MTM_STAGE	CUST_NUM	INTERFACE.V_API_MTM_REVAL.CUST_NUM -> BASE_DATA.CUST_NUM -> SESSION.T_MTM_STAGE.CUST_NUM	2	PROPAGATED_LINEAGE	PARSER
INTERFACE.V_API_MTM_REVAL	DEAL_NUM	SESSION.T_MTM_STAGE	DEAL_NUM	INTERFACE.V_API_MTM_REVAL.DEAL_NUM -> BASE_DATA.DEAL_NUM -> SESSION.T_MTM_STAGE.DEAL_NUM	2	PROPAGATED_LINEAGE	PARSER
INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	SESSION.T_MTM_STAGE	DEAL_TYPE	INTERFACE.V_API_MTM_REVAL.DEAL_TYPE -> BASE_DATA.DEAL_TYPE -> SESSION.T_MTM_STAGE.DEAL_TYPE	2	PROPAGATED_LINEAGE	PARSER
INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT -> BASE_DATA.CUR_MTM_AMT -> SESSION.T_MTM_STAGE.CUR_MTM_AMT	2	PROPAGATED_LINEAGE	PARSER

SESSION.T_MTM_STAGE	CUST_NUM	SESSION.T_MTM_STAGE_ALL	CUST_NUM	SESSION.T_MTM_STAGE.CUST_NUM -> SESSION.T_MTM_STAGE_ALL.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_NUM	SESSION.T_MTM_STAGE_ALL	DEAL_NUM	SESSION.T_MTM_STAGE.DEAL_NUM -> SESSION.T_MTM_STAGE_ALL.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_TYPE	SESSION.T_MTM_STAGE_ALL	DEAL_TYPE	SESSION.T_MTM_STAGE.DEAL_TYPE -> SESSION.T_MTM_STAGE_ALL.DEAL_TYPE	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	CUR_MTM_AMT	SESSION.T_MTM_STAGE_ALL	CUR_MTM_AMT	SESSION.T_MTM_STAGE.CUR_MTM_AMT -> SESSION.T_MTM_STAGE_ALL.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER

SESSION.T_MTM_STAGE	CUST_NUM	INTERFACE.API_MTM_REVAL	CUST_NUM	SESSION.T_MTM_STAGE.CUST_NUM -> INTERFACE.API_MTM_REVAL.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_NUM	INTERFACE.API_MTM_REVAL	DEAL_NUM	SESSION.T_MTM_STAGE.DEAL_NUM -> INTERFACE.API_MTM_REVAL.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_TYPE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	SESSION.T_MTM_STAGE.DEAL_TYPE -> INTERFACE.API_MTM_REVAL.DEAL_TYPE	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	CUR_MTM_AMT	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	SESSION.T_MTM_STAGE.CUR_MTM_AMT -> INTERFACE.API_MTM_REVAL.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER

SESSION.T_MTM_STAGE_ALL	CUST_NUM	INTERFACE.API_MTM_REVAL_STAR	CUST_NUM	SESSION.T_MTM_STAGE_ALL.CUST_NUM -> INTERFACE.API_MTM_REVAL_STAR.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE_ALL	DEAL_NUM	INTERFACE.API_MTM_REVAL_STAR	DEAL_NUM	SESSION.T_MTM_STAGE_ALL.DEAL_NUM -> INTERFACE.API_MTM_REVAL_STAR.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE_ALL	DEAL_TYPE	INTERFACE.API_MTM_REVAL_STAR	DEAL_TYPE	SESSION.T_MTM_STAGE_ALL.DEAL_TYPE -> INTERFACE.API_MTM_REVAL_STAR.DEAL_TYPE	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE_ALL	CUR_MTM_AMT	INTERFACE.API_MTM_REVAL_STAR	CUR_MTM_AMT	SESSION.T_MTM_STAGE_ALL.CUR_MTM_AMT -> INTERFACE.API_MTM_REVAL_STAR.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER

FOS.API_MTM_REVAL	CUSTOMER_NUMBER	INTERFACE.API_MTM_REVAL_STAR	CUST_NUM	FOS.API_MTM_REVAL.CUSTOMER_NUMBER -> INTERFACE.V_API_MTM_REVAL.CUST_NUM -> BASE_DATA.CUST_NUM -> SESSION.T_MTM_STAGE.CUST_NUM -> SESSION.T_MTM_STAGE_ALL.CUST_NUM -> INTERFACE.API_MTM_REVAL_STAR.CUST_NUM	5	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	DEAL_NUMBER	INTERFACE.API_MTM_REVAL_STAR	DEAL_NUM	FOS.API_MTM_REVAL.DEAL_NUMBER -> INTERFACE.V_API_MTM_REVAL.DEAL_NUM -> BASE_DATA.DEAL_NUM -> SESSION.T_MTM_STAGE.DEAL_NUM -> SESSION.T_MTM_STAGE_ALL.DEAL_NUM -> INTERFACE.API_MTM_REVAL_STAR.DEAL_NUM	5	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	DEAL_TYPE	INTERFACE.API_MTM_REVAL_STAR	DEAL_TYPE	FOS.API_MTM_REVAL.DEAL_TYPE -> INTERFACE.V_API_MTM_REVAL.DEAL_TYPE -> BASE_DATA.DEAL_TYPE -> SESSION.T_MTM_STAGE.DEAL_TYPE -> SESSION.T_MTM_STAGE_ALL.DEAL_TYPE -> INTERFACE.API_MTM_REVAL_STAR.DEAL_TYPE	5	PROPAGATED_LINEAGE	PARSER
FOS.API_MTM_REVAL	MTM_AMOUNT	INTERFACE.API_MTM_REVAL_STAR	CUR_MTM_AMT	FOS.API_MTM_REVAL.MTM_AMOUNT -> INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT -> BASE_DATA.CUR_MTM_AMT -> SESSION.T_MTM_STAGE.CUR_MTM_AMT -> SESSION.T_MTM_STAGE_ALL.CUR_MTM_AMT -> INTERFACE.API_MTM_REVAL_STAR.CUR_MTM_AMT	5	PROPAGATED_LINEAGE	PARSER

SESSION.T_MTM_STAGE	CUST_NUM	INTERFACE.V_API_MTM_REVAL	CUST_NUM	SESSION.T_MTM_STAGE.CUST_NUM -> INTERFACE.V_API_MTM_REVAL.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_NUM	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	SESSION.T_MTM_STAGE.DEAL_NUM -> INTERFACE.V_API_MTM_REVAL.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_TYPE	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	SESSION.T_MTM_STAGE.DEAL_TYPE -> INTERFACE.V_API_MTM_REVAL.DEAL_TYPE	1	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	CUR_MTM_AMT	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	SESSION.T_MTM_STAGE.CUR_MTM_AMT -> INTERFACE.V_API_MTM_REVAL.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER

SESSION.T_MTM_STAGE	CUST_NUM	RPT.MTM_REVAL_AUDIT	CUST_NUM	SESSION.T_MTM_STAGE.CUST_NUM -> RPT.PR_AUDIT_MTM_REVAL.P_CUST_NUM -> RPT.MTM_REVAL_AUDIT.CUST_NUM	2	PROPAGATED_LINEAGE	PARSER
SESSION.T_MTM_STAGE	DEAL_NUM	RPT.MTM_REVAL_AUDIT	DEAL_NUM	SESSION.T_MTM_STAGE.DEAL_NUM -> RPT.PR_AUDIT_MTM_REVAL.P_DEAL_NUM -> RPT.MTM_REVAL_AUDIT.DEAL_NUM	2	PROPAGATED_LINEAGE	PARSER

INTERFACE.API_MTM_REVAL	CUST_NUM	INTERFACE.MTM_REVAL_TMP_COPY	CUST_NUM	INTERFACE.API_MTM_REVAL.CUST_NUM -> INTERFACE.MTM_REVAL_TMP_COPY.CUST_NUM	1	PROPAGATED_LINEAGE	PARSER
INTERFACE.API_MTM_REVAL	DEAL_NUM	INTERFACE.MTM_REVAL_TMP_COPY	DEAL_NUM	INTERFACE.API_MTM_REVAL.DEAL_NUM -> INTERFACE.MTM_REVAL_TMP_COPY.DEAL_NUM	1	PROPAGATED_LINEAGE	PARSER
INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	INTERFACE.MTM_REVAL_TMP_COPY	CUR_MTM_AMT	INTERFACE.API_MTM_REVAL.CUR_MTM_AMT -> INTERFACE.MTM_REVAL_TMP_COPY.CUR_MTM_AMT	1	PROPAGATED_LINEAGE	PARSER
  
===================================
    source_object_type	source_object	source_field	target_object_type	target_object	target_field	relationship	line_no	line_content	persistent_impact_objects	intermediate_objects	confidence
VIEW_DDL	ddl_views.sql		VIEW	INTERFACE.V_API_MTM_REVAL		CREATE_VIEW	1	CREATE VIEW INTERFACE.V_API_MTM_REVAL AS	INTERFACE.V_API_MTM_REVAL		REGEX
VIEW_DDL	ddl_views.sql		TABLE	FOS.API_MTM_REVAL		SELECT_TABLE	7	FROM FOS.API_MTM_REVAL F	FOS.API_MTM_REVAL		PARSER
VIEW_DDL	ddl_views.sql	CUSTOMER_NUMBER	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	CREATE_VIEW_MAP	3	F.CUSTOMER_NUMBER AS CUST_NUM	FOS.API_MTM_REVAL,INTERFACE.V_API_MTM_REVAL		PARSER
VIEW_DDL	ddl_views.sql	DEAL_NUMBER	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_NUM	CREATE_VIEW_MAP	4	F.DEAL_NUMBER AS DEAL_NUM	FOS.API_MTM_REVAL,INTERFACE.V_API_MTM_REVAL		PARSER
VIEW_DDL	ddl_views.sql	DEAL_TYPE	VIEW	INTERFACE.V_API_MTM_REVAL	DEAL_TYPE	CREATE_VIEW_MAP	5	F.DEAL_TYPE AS DEAL_TYPE	FOS.API_MTM_REVAL,INTERFACE.V_API_MTM_REVAL		PARSER
VIEW_DDL	ddl_views.sql	MTM_AMOUNT	VIEW	INTERFACE.V_API_MTM_REVAL	CUR_MTM_AMT	CREATE_VIEW_MAP	6	F.MTM_AMOUNT AS CUR_MTM_AMT	FOS.API_MTM_REVAL,INTERFACE.V_API_MTM_REVAL		PARSER
VIEW_DDL	ddl_views.sql	LAST_UPDATE_TS	VIEW	INTERFACE.V_API_MTM_REVAL	LAST_UPD_TS	CREATE_VIEW_MAP	7	F.LAST_UPDATE_TS AS LAST_UPD_TS	FOS.API_MTM_REVAL,INTERFACE.V_API_MTM_REVAL		PARSER

FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE		TABLE	CCL.CODE_MAP		SELECT_TABLE	13	FROM CCL.CODE_MAP	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_VALUE	TABLE	CCL.CODE_MAP	CODE_VALUE	SELECT_FIELD	12	SELECT CODE_VALUE	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_CATEGORY	TABLE	CCL.CODE_MAP	CODE_CATEGORY	WHERE	14	WHERE CODE_CATEGORY = P_CODE_CATEGORY	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_SUB_CATEGORY	TABLE	CCL.CODE_MAP	CODE_SUB_CATEGORY	WHERE	15	AND CODE_SUB_CATEGORY = P_CODE_SUB_CATEGORY	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_TYPE	TABLE	CCL.CODE_MAP	CODE_TYPE	WHERE	16	AND CODE_TYPE = P_CODE_TYPE	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	KEY1	TABLE	CCL.CODE_MAP	KEY1	WHERE	17	AND KEY1 = P_KEY1	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	KEY2	TABLE	CCL.CODE_MAP	KEY2	WHERE	18	AND KEY2 = P_KEY2	CCL.CODE_MAP		PARSER
FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE	CODE_VALUE	TABLE	CCL.CODE_MAP	CODE_VALUE	RETURN_VALUE	12	SELECT CODE_VALUE	CCL.CODE_MAP		PARSER

FUNCTION	INTERFACE.FN_REL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		SELECT_VIEW	11	FROM INTERFACE.V_API_MTM_REVAL V	INTERFACE.V_API_MTM_REVAL		PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	SELECT_FIELD	9	SELECT TRIM(V.CUST_NUM) || '-' || ...	INTERFACE.V_API_MTM_REVAL		PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	SELECT_EXPR	9	SELECT TRIM(V.CUST_NUM) || '-' || ...	INTERFACE.V_API_MTM_REVAL		PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	WHERE	12	WHERE V.CUST_NUM = P_CUST_NUM	INTERFACE.V_API_MTM_REVAL		PARSER
FUNCTION	INTERFACE.FN_REL_DEMO		FUNCTION	INTERFACE.FN_GET_CODE_MAP_VALUE		CALL_FUNCTION	10	INTERFACE.FN_GET_CODE_MAP_VALUE('MTM','STATUS','DEFAULT','A','B')			PARSER
FUNCTION	INTERFACE.FN_REL_DEMO	CUST_NUM	VIEW	INTERFACE.V_API_MTM_REVAL	CUST_NUM	RETURN_VALUE	9	SELECT TRIM(V.CUST_NUM) || '-' || ...	INTERFACE.V_API_MTM_REVAL		PARSER

PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT		INSERT_TABLE	9	INSERT INTO RPT.MTM_REVAL_AUDIT	RPT.MTM_REVAL_AUDIT		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	AUDIT_ID	INSERT_TARGET_COL	11	AUDIT_ID	RPT.MTM_REVAL_AUDIT		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	CUST_NUM	INSERT_TARGET_COL	12	CUST_NUM	RPT.MTM_REVAL_AUDIT		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	DEAL_NUM	INSERT_TARGET_COL	13	DEAL_NUM	RPT.MTM_REVAL_AUDIT		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	ACTION_CD	INSERT_TARGET_COL	14	ACTION_CD	RPT.MTM_REVAL_AUDIT		PARSER
PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		TABLE	RPT.MTM_REVAL_AUDIT	AUDIT_TS	INSERT_TARGET_COL	15	AUDIT_TS	RPT.MTM_REVAL_AUDIT		PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		CREATE_TABLE	8	DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE		SESSION.T_MTM_STAGE	REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		CREATE_TABLE	17	DECLARE GLOBAL TEMPORARY TABLE SESSION.T_MTM_STAGE_ALL		SESSION.T_MTM_STAGE_ALL	REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		FUNCTION	INTERFACE.FN_REL_DEMO		CALL_FUNCTION	27	SET V_STATUS = INTERFACE.FN_REL_DEMO(P_CUST_NUM)			PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE		INSERT_TABLE	29	INSERT INTO SESSION.T_MTM_STAGE		SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	INSERT_TARGET_COL	31	CUST_NUM		SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	INSERT_TARGET_COL	32	DEAL_NUM		SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	INSERT_TARGET_COL	33	DEAL_TYPE		SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INSERT_TARGET_COL	34	CUR_MTM_AMT		SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		CTE	BASE_DATA		CTE_DEFINE	35	WITH BASE_DATA AS		BASE_DATA	REGEX
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		UNION_INPUT	43	FROM INTERFACE.V_API_MTM_REVAL V	INTERFACE.V_API_MTM_REVAL	BASE_DATA	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		UNION_INPUT	52	FROM INTERFACE.API_MTM_REVAL I	INTERFACE.API_MTM_REVAL	BASE_DATA	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		CTE	BASE_DATA		CTE_READ	58	FROM BASE_DATA B		BASE_DATA	REGEX

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	CTE	BASE_DATA	CUST_NUM	INSERT_SELECT_MAP	55	B.CUST_NUM		BASE_DATA,SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	CTE	BASE_DATA	DEAL_NUM	INSERT_SELECT_MAP	56	B.DEAL_NUM		BASE_DATA,SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	CTE	BASE_DATA	DEAL_TYPE	INSERT_SELECT_MAP	57	B.DEAL_TYPE		BASE_DATA,SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	CTE	BASE_DATA	CUR_MTM_AMT	INSERT_SELECT_MAP	58	B.CUR_MTM_AMT		BASE_DATA,SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		INSERT_TABLE	60	INSERT INTO SESSION.T_MTM_STAGE_ALL		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUST_NUM	INSERT_TARGET_COL	62	CUST_NUM		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_NUM	INSERT_TARGET_COL	63	DEAL_NUM		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_TYPE	INSERT_TARGET_COL	64	DEAL_TYPE		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUR_MTM_AMT	INSERT_TARGET_COL	65	CUR_MTM_AMT		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	INSERT_SELECT_MAP	67	S.CUST_NUM		SESSION.T_MTM_STAGE,SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	INSERT_SELECT_MAP	68	S.DEAL_NUM		SESSION.T_MTM_STAGE,SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	INSERT_SELECT_MAP	69	S.DEAL_TYPE		SESSION.T_MTM_STAGE,SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INSERT_SELECT_MAP	70	S.CUR_MTM_AMT		SESSION.T_MTM_STAGE,SESSION.T_MTM_STAGE_ALL	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		INSERT_TABLE	72	INSERT INTO INTERFACE.API_MTM_REVAL	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	INSERT_SELECT_MAP	82	S.CUST_NUM	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	INSERT_SELECT_MAP	83	S.DEAL_NUM	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	INSERT_SELECT_MAP	84	S.DEAL_TYPE	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	INSERT_SELECT_MAP	85	S.CUR_MTM_AMT	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL_STAR		INSERT_TABLE	88	INSERT INTO INTERFACE.API_MTM_REVAL_STAR	INTERFACE.API_MTM_REVAL_STAR		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		SESSION_TABLE	SESSION.T_MTM_STAGE_ALL		SELECT_TABLE	90	FROM SESSION.T_MTM_STAGE_ALL		SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUST_NUM	INSERT_SELECT_MAP	89	SELECT *	INTERFACE.API_MTM_REVAL_STAR	SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_NUM	INSERT_SELECT_MAP	89	SELECT *	INTERFACE.API_MTM_REVAL_STAR	SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	DEAL_TYPE	INSERT_SELECT_MAP	89	SELECT *	INTERFACE.API_MTM_REVAL_STAR	SESSION.T_MTM_STAGE_ALL	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE_ALL	CUR_MTM_AMT	INSERT_SELECT_MAP	89	SELECT *	INTERFACE.API_MTM_REVAL_STAR	SESSION.T_MTM_STAGE_ALL	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		INSERT_VIEW	92	INSERT INTO INTERFACE.V_API_MTM_REVAL	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUSTOMER_NUMBER	TABLE	FOS.API_MTM_REVAL	CUSTOMER_NUMBER	INSERT_SELECT_MAP	100	CUSTOMER_NUMBER	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUMBER	TABLE	FOS.API_MTM_REVAL	DEAL_NUMBER	INSERT_SELECT_MAP	101	DEAL_NUMBER	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	TABLE	FOS.API_MTM_REVAL	DEAL_TYPE	INSERT_SELECT_MAP	102	DEAL_TYPE	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	MTM_AMOUNT	TABLE	FOS.API_MTM_REVAL	MTM_AMOUNT	INSERT_SELECT_MAP	103	MTM_AMOUNT	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	LAST_UPDATE_TS	TABLE	FOS.API_MTM_REVAL	LAST_UPDATE_TS	INSERT_SELECT_MAP	104	LAST_UPDATE_TS	INTERFACE.V_API_MTM_REVAL		PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		UPDATE_TABLE	107	UPDATE INTERFACE.API_MTM_REVAL T	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	UPDATE_SET_MAP	111	SELECT S.CUR_MTM_AMT	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		UPDATE_VIEW	118	UPDATE INTERFACE.V_API_MTM_REVAL V	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		DELETE_TABLE	122	DELETE FROM INTERFACE.API_MTM_REVAL	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		DELETE_VIEW	125	DELETE FROM INTERFACE.V_API_MTM_REVAL	INTERFACE.V_API_MTM_REVAL		PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.API_MTM_REVAL		MERGE_TABLE	128	MERGE INTO INTERFACE.API_MTM_REVAL T	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_SET_MAP	133	T.CUR_MTM_AMT = S.CUR_MTM_AMT	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	CUST_NUM	MERGE_INSERT_MAP	146	S.CUST_NUM	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_NUM	MERGE_INSERT_MAP	147	S.DEAL_NUM	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_TYPE	SESSION_TABLE	SESSION.T_MTM_STAGE	DEAL_TYPE	MERGE_INSERT_MAP	148	S.DEAL_TYPE	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_INSERT_MAP	149	S.CUR_MTM_AMT	INTERFACE.API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		VIEW	INTERFACE.V_API_MTM_REVAL		MERGE_VIEW	155	MERGE INTO INTERFACE.V_API_MTM_REVAL V	INTERFACE.V_API_MTM_REVAL		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	SESSION_TABLE	SESSION.T_MTM_STAGE	CUR_MTM_AMT	MERGE_SET_MAP	160	V.CUR_MTM_AMT = S.CUR_MTM_AMT	INTERFACE.V_API_MTM_REVAL	SESSION.T_MTM_STAGE	PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		PROCEDURE	RPT.PR_AUDIT_MTM_REVAL		CALL_PROCEDURE	180	CALL RPT.PR_AUDIT_MTM_REVAL(P_CUST_NUM, 'D001', 'DONE')			PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_TMP_COPY		INSERT_TABLE	182	INSERT INTO INTERFACE.MTM_REVAL_TMP_COPY	INTERFACE.MTM_REVAL_TMP_COPY		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUST_NUM	TABLE	INTERFACE.API_MTM_REVAL	CUST_NUM	INSERT_SELECT_MAP	190	CUST_NUM	INTERFACE.MTM_REVAL_TMP_COPY		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	INSERT_SELECT_MAP	191	DEAL_NUM	INTERFACE.MTM_REVAL_TMP_COPY		PARSER
PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO	CUR_MTM_AMT	TABLE	INTERFACE.API_MTM_REVAL	CUR_MTM_AMT	INSERT_SELECT_MAP	192	CUR_MTM_AMT	INTERFACE.MTM_REVAL_TMP_COPY		PARSER

PROCEDURE	INTERFACE.PI_API_MTM_REVAL_DEMO		TABLE	INTERFACE.MTM_REVAL_HIST		TRUNCATE_TABLE	195	TRUNCATE TABLE INTERFACE.MTM_REVAL_HIST IMMEDIATE	INTERFACE.MTM_REVAL_HIST		REGEX

PROCEDURE	EXTRA_SELECT_PATTERNS		TABLE	INTERFACE.API_MTM_REVAL		SELECT_TABLE	4	FROM INTERFACE.API_MTM_REVAL I	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS		TABLE	FOS.API_MTM_REVAL		SELECT_TABLE	5	JOIN FOS.API_MTM_REVAL F	FOS.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	DEAL_NUM	TABLE	INTERFACE.API_MTM_REVAL	DEAL_NUM	JOIN_ON	6	ON I.DEAL_NUM = F.DEAL_NUMBER	INTERFACE.API_MTM_REVAL,FOS.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	DEAL_NUMBER	TABLE	FOS.API_MTM_REVAL	DEAL_NUMBER	JOIN_ON	6	ON I.DEAL_NUM = F.DEAL_NUMBER	INTERFACE.API_MTM_REVAL,FOS.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	STATUS_CD	TABLE	INTERFACE.API_MTM_REVAL	STATUS_CD	WHERE	7	WHERE I.STATUS_CD = 'ACTIVE'	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	GROUP_BY	8	GROUP BY I.DEAL_TYPE	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	HAVING	9	HAVING COUNT(*) > 1	INTERFACE.API_MTM_REVAL		PARSER
PROCEDURE	EXTRA_SELECT_PATTERNS	DEAL_TYPE	TABLE	INTERFACE.API_MTM_REVAL	DEAL_TYPE	ORDER_BY	10	ORDER BY I.DEAL_TYPE	INTERFACE.API_MTM_REVAL		PARSER

PROCEDURE	EXTRA_UNKNOWN		UNKNOWN	UNKNOWN_DYNAMIC_SQL		UNKNOWN	1	EXECUTE IMMEDIATE 'DELETE FROM INTERFACE.API_MTM_REVAL WHERE STATUS_CD = ''X'''	INTERFACE.API_MTM_REVAL		DYNAMIC_LOW_CONFIDENCE
