# IBM MQ Global Configuration (mapped by IbmMqProperties)
ibm:
  mq:
    queueManager: "QM1"
    channel: "DEV.APP.SVRCONN"
    connName: "localhost(1414)"
    user: "app"
    password: "pass"
    queue: "commonQueue"

# Kafka Common Configuration
kafkaConfig:
  kafka-1:
    bootstrap-servers: "xx:9092"
    security.protocol: "SASL_SSL"
    sasl.mechanism: "SCRAM-SHA-512"
    sasl.jaas.config: >
      org.apache.kafka.common.security.scram.ScramLoginModule required
      username="kafka_consumer_user"
      password="YOUR_CONSUMER_PASSWORD";
    consumers:
      consumer-1:
        group-id: "share-broker-order-domain-event"
        auto-offset-reset: "earliest"
      consumer-2:
        group-id: "share-2-domain-event"
        auto-offset-reset: "earliest"
    producers:
      producer-1:
        client-id: "xx-service"
        acks: "all"
        retries: 0

# Unified Kafka Wrapper Configuration
kafka-wrapper:
  default-thread-pool:
    coreSize: 10
    maxSize: 50
    keepAliveTime: 60
    queueCapacity: 100
  sharedPoolSize: 20
  products:
    equity:
      broker: "${kafkaConfig.kafka-1.bootstrap-servers}"
      security:
        protocol: "${kafkaConfig.kafka-1.security.protocol}"
        saslMechanism: "${kafkaConfig.kafka-1.sasl.mechanism}"
        saslJaasConfig: "${kafkaConfig.kafka-1.sasl.jaas.config}"
      consumer:
        groupId: "${kafkaConfig.kafka-1.consumers.consumer-1.group-id}"
        autoOffsetReset: "${kafkaConfig.kafka-1.consumers.consumer-1.auto-offset-reset}"
      threadPool:
        coreSize: 15
        maxSize: 60
        keepAliveTime: 120
        queueCapacity: 200
      topics:
        topic-1:
          name: "equity-topic-wrapper"
          concurrency: 3
          threadPool:
            coreSize: 5
            maxSize: 20
            keepAliveTime: 120
            queueCapacity: 100
          eventProcessorMapping:
            orderCreated: "equityCustomProcessor,genericProcessor"
            orderCancelled: "genericProcessor"
    fund:
      broker: "yy:9092"
      security:
        protocol: "SASL_SSL"
        saslMechanism: "SCRAM-SHA-512"
        saslJaasConfig: >
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username="fund_kafka_user"
          password="YOUR_FUND_PASSWORD";
      consumer:
        groupId: "${kafkaConfig.kafka-1.consumers.consumer-2.group-id}"
        autoOffsetReset: "${kafkaConfig.kafka-1.consumers.consumer-2.auto-offset-reset}"
      topics:
        topic-1:
          name: "fund-topic-wrapper"
          concurrency: 2
          threadPool:
            maxSize: 3
            queueCapacity: 80
            keepAliveTime: 60
          eventProcessorMapping:
            subscriptionCreated: "fundCustomProcessor,genericProcessor"
            subscriptionCancelled: "genericProcessor"

# Kafka Business Configuration for Dispatcher (MQ -> Kafka)
kafkaDispatcher:
  equity:
    broker: "${kafkaConfig.kafka-1.bootstrap-servers}"
    sourceQueue: "equityDispatcherQueue"
    targetTopic: "equity-topic-dispatcher"
    concurrency: 2